import numpy as np

ACTION_LEFT = 0
ACTION_TOP = 1
ACTION_RIGHT = 2
ACTION_DOWN = 3
ACTION_NAME = ['LEFT', 'TOP', 'RIGHT', 'DOWN']
ACTION_SIZE = len(ACTION_NAME)
# ACTION_LIST = np.array([ACTION_LEFT, ACTION_TOP, ACTION_RIGHT, ACTION_DOWN])
